SELECT t1.dtRef,
       t1.IdCliente,
       t1.idadeDias, 
       t1.qtdeAtivacaoVida,
       t1.qtdeAtivacaoD7,
       t1.qtdeAtivacaoD14,
       t1.qtdeAtivacaoD28,
       t1.qtdeAtivacaoD56,
       t1.qtdeTransacaoVida,
       t1.qtdeTransacaoD7,
       t1.qtdeTransacaoD14,
       t1.qtdeTransacaoD28,
       t1.qtdeTransacaoD56,
       t1.saldoVida,
       t1.saldoVidaD7,
       t1.saldoVidaD14,
       t1.saldoVidaD28,
       t1.saldoVidaD56,
       t1.qtdePontosPosVida,
       t1.qtdePontosPosVidaD7,
       t1.qtdePontosPosVidaD14,
       t1.qtdePontosPosVidaD28,
       t1.qtdePontosPosVidaD56,
       t1.qtdePontosNegVida,
       t1.qtdePontosNegVidaD7,
       t1.qtdePontosNegVidaD14,
       t1.qtdePontosNegVidaD28,
       t1.qtdePontosNegVidaD56,
       t1.qtdeTransacaoManha,
       t1.qtdeTransacaoTarde,
       t1.qtdeTransacaoNoite,
       t1.pctTransacaoManha, 
       t1.pctTransacaoTarde, 
	   t1.pctTransacaoNoite, 
	   t1.QtdeTransacaoDiaVida, 
	   t1.QtdeTransacaoDiaD7, 
	   t1.QtdeTransacaoDiaD14, 
	   t1.QtdeTransacaoDiaD28, 
	   t1.QtdeTransacaoDiaD56, 
	   t1.pctAtivacaoMAU, 
	   t1.qtdehorasVida, 
	   t1.qtdehorasD7, 
	   t1.qtdehorasD14, 
	   t1.qtdehorasD28, 
	   t1.qtdehorasD56, 
	   t1.avgIntervaloDiasVida, 
	   t1.avgIntervaloDiasD28, 
	   t1.qtdeChatMessage, 
	   t1.qtdeAirflowLover, 
	   t1.qtdeRLover, 
	   t1.qtdeResgatarPonei, 
	   t1.qtdeListaPresenca, 
	   t1.qtdePresencaStreak, 
	   t1.qtdeTrocaPontosStreamElements, 
	   t1.qtdeReembolsoStreamElements, 
	   t1.qtdeRPG, 
	   t1.qtdeChurnModel,
       t2.DiasComFrequencia, 
	   t2.descLifeCycleAtual, 
	   t2.descLifeCycleD28, 
	   t2.pctCurioso, 
	   t2.pctFiel, 
	   t2.pctTurista, 
	   t2.pctDesencantada, 
	   t2.pctZumbi, 
	   t2.pctReconquistado, 
	   t2.pctReborn, 
	   t2.avgFreqGrupo, 
	   t2.ratioFreqGrupo,
       t3.qtdeCursosCompletos, 
	   t3.qtdeCursosIncompletos, 
	   t3.carreira, 
	   t3.coletaDados2024, 
	   t3.dsDatabricks2024, 
	   t3.dsPontos2024, 
	   t3.estatistica2024, 
	   t3.estatistica2025, 
	   t3.github2024, 
	   t3.github2025, 
	   t3.iaCanal2025, 
	   t3.lagoMago2024, 
	   t3.loyaltyPredict2025, 
	   t3.machineLearning2025, 
	   t3.matchmakingTramparDeCasa2024, 
	   t3.ml2024, 
	   t3.mlflow2025, 
	   t3.pandas2024, 
	   t3.pandas2025, 
	   t3.python2024, 
	   t3.python2025, 
	   t3.sql2020, 
	   t3.sql2025, 
	   t3.streamlit2025, 
	   t3.tramparLakehouse2024, 
	   t3.tseAnalytics2024, 
	   t3.qtdeDiasUltimaAtividade

FROM fs_transacional AS t1

LEFT JOIN fs_life_cycle AS t2
ON t1.IdCliente = t2.IdCliente
AND t1.DtRef = t2.DtRef

LEFT JOIN fs_education AS t3
ON t1.IdCliente = t3.IdCliente
AND t1.DtRef = t3.DtRef

WHERE t1.DtRef = (SELECT MAX(DtRef) FROM fs_transacional)